name: build-push-cache
on:
  workflow_call:
    inputs:
      cache_url:
        type: string
        required: false
      builder_attr:
        type: string
        required: false
    secrets:
      BUILDER_SSH_KEY:
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
